from __future__ import annotations

import argparse
import json
from pathlib import Path
from statistics import median
from typing import Any


SIGNALS = (
    "microprice_edge",
    "momentum_100ms",
    "momentum_500ms",
    "spread",
    "immediate_move_50ms",
)


def _to_float(value: Any) -> float | None:
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _signal_stats(rows: list[dict[str, Any]], signal: str) -> dict[str, float]:
    values = [_to_float(row.get(signal)) for row in rows]
    clean = [v for v in values if v is not None]
    if not clean:
        return {"mean": 0.0, "median": 0.0, "count": 0.0}
    return {
        "mean": sum(clean) / float(len(clean)),
        "median": float(median(clean)),
        "count": float(len(clean)),
    }


def _classify_separation(best_mean: float, worst_mean: float, diff: float) -> str:
    denom = max(abs(best_mean), abs(worst_mean), 1e-12)
    rel = abs(diff) / denom
    if rel < 0.10:
        return "USELESS (weak separation)"
    if rel < 0.30:
        return "MODERATE"
    return "PREDICTIVE (strong separation)"


def _immediate_alignment_pct(rows: list[dict[str, Any]]) -> float:
    aligned = 0
    total = 0
    for row in rows:
        side = str(row.get("side", "")).upper()
        move = _to_float(row.get("immediate_move_50ms"))
        if move is None:
            continue
        if side not in {"LONG", "SHORT"}:
            continue
        total += 1
        if (side == "LONG" and move > 0.0) or (side == "SHORT" and move < 0.0):
            aligned += 1
    return (100.0 * float(aligned) / float(total)) if total > 0 else 0.0


def analyze(payload: dict[str, Any]) -> str:
    best = payload.get("best", [])
    worst = payload.get("worst", [])
    if not isinstance(best, list) or not isinstance(worst, list):
        raise ValueError("Invalid JSON structure: expected keys 'best' and 'worst' as lists.")

    lines: list[str] = []
    lines.append("=== Round-Trip Signal Separation Report ===")
    lines.append(f"best_count={len(best)} | worst_count={len(worst)}")
    lines.append("")

    for signal in SIGNALS:
        b = _signal_stats(best, signal)
        w = _signal_stats(worst, signal)
        diff = b["mean"] - w["mean"]
        usefulness = _classify_separation(b["mean"], w["mean"], diff)
        lines.append(f"{signal}:")
        lines.append(f"  best_mean   = {b['mean']:.8f}")
        lines.append(f"  worst_mean  = {w['mean']:.8f}")
        lines.append(f"  diff        = {diff:.8f}")
        lines.append(f"  best_median = {b['median']:.8f}")
        lines.append(f"  worst_median= {w['median']:.8f}")
        lines.append(f"  verdict     = {usefulness}")
        lines.append("")

    best_align = _immediate_alignment_pct(best)
    worst_align = _immediate_alignment_pct(worst)
    lines.append("immediate_move_50ms alignment with trade direction:")
    lines.append(f"  best_aligned_pct  = {best_align:.2f}%")
    lines.append(f"  worst_aligned_pct = {worst_align:.2f}%")
    lines.append(f"  diff_pct          = {best_align - worst_align:.2f} pp")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Compare BEST vs WORST round-trips from rt_extremes.json")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("rt_extremes.json"),
        help="Path to JSON generated by export_rt_extremes.py",
    )
    args = parser.parse_args()

    payload = json.loads(args.input.read_text(encoding="utf-8"))
    report = analyze(payload)
    print(report)


if __name__ == "__main__":
    main()
